name: w3gx_dart
description: w3gx dart client
version: 0.0.1
homepage:

environment:
    sdk: ">=2.18.1 <3.0.0"
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter
    web_socket_channel: ^2.2.0
    uuid: ^3.0.6

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
